import {
  AddRoomType,
  HotelAmenitiesType,
  HotelBasicInfoType,
  HotelPolicyType,
} from '@/types';

export const defaultBasicInfo: HotelBasicInfoType = {
  description: '',
  website: '',
  address: '',
  city: '',
  state: '',
  country: '',
  zipCode: '',
  lng: 0,
  lat: 0,
  hotelType: 'HOTEL',
  roomUnitTotal: 1,
  acceptedCurrency: 'NGN',
};

export const defaultPolicies: HotelPolicyType = {
  paymentMethods: [],
  isDepositRequired: false,
  depositAmount: 0,
  isTaxIncludedInRoomRates: false,
  cancellationPolicy: 'FREE_CANCELLATION',
  smokingPolicy: 'NO_SMOKING',

  isFrontDesk: false,
  isFrontDeskEveryDay: true,
  isFrontDeskOpen24Hours: false,
  frontDeskScheduleStartDay: 'MONDAY',
  frontDeskScheduleEndDay: 'FRIDAY',
  frontDeskStartTime: '06:00',
  frontDeskEndTime: '06:00',
  isSelfCheckIn: false,
  selfCheckInType: 'ACCESS_CODE',

  checkInStartTime: '06:00',
  checkInEndTime: '06:00',
  isOpen24Hours: false,
  isLateCheckIn: false,
  lateCheckInType: 'FREE',

  surchargeType: 'AMOUNT',
  surchargeAmount: 0,
  lateCheckInStartTime: '06:00',
  lateCheckInEndTime: '06:00',
  isAdvancedNoticeCheckIn: false,
  advanceNoticeCheckInTime: '06:00',

  checkOutTime: '06:00',
  minCheckInAgeAllowed: 18,
  hasAdditionalPolicy: false,
  additionalPolicy: [],

  isPetAllowed: false,
  isPetSurcharged: false,
  petSurchargeAmount: 0,
  petSurchargeType: undefined,
  petSurchargeDuration: undefined,
  isMaxFeePerStay: false,
  isPetFeeVaried: false,
  maxFeePerStayAmount: 0,
  allowedPetType: undefined,
  isPetRestricted: false,
  petRestrictionType: [],
  isMaxWeightPerPet: false,
  petMaxWeight: 0,
  isPetDeposit: false,
  petDepositType: undefined,
  petDepositAmount: undefined,
  isPetCleaningFee: false,
  petCleaningFee: 0,
  petFriendlyFeatures: [],
};

export const defaultHotelAmenities: HotelAmenitiesType = {
  isWifi: false,
  wifiArea: [],
  roomWifiChargeType: 'FREE',
  roomWifiSpeed: 'MBPS_25',
  roomWifiSurchargeAmout: 0,
  roomWifiSurchargeDuration: 'PER_DAY',
  roomDeviceLimited: false,
  roomDeviceLimitNumber: 1,
  publicWifiChargeType: 'FREE',
  publicWifiSpeed: 'MBPS_25',
  publicWifiSurchargeAmout: 0,
  publicWifiSurchargeDuration: 'PER_DAY',
  publicDeviceLimited: false,
  publicDeviceLimitNumber: 0,
  isBreakfast: false,
  breakfastChargeType: 'FREE',
  breakfastSurchargeAmount: 0,
  breakfastSchedule: 'DAILY',
  breakfastStartTime: '',
  breakfastEndTime: '',
};

export const defaultRooomValues: AddRoomType = {
  name: '',
  roomType: 'SINGLE',
  roomImages: [],
  roomSize: 0,
  roomSizeUnit: 'SQUARE_FEET',
  totalRooms: 0,
  baseRate: 0,
  pricingModel: 'PER_DAY',
  maxOccupancy: 1,
  bedTotal: 1,
  bedType: 'BUNK',
  bathroomType: 'PRIVATE',
  bathroomNumber: 1,
  showerType: 'SHOWER',
  isTowelProvided: false,
  climateControl: [],
  isRoomView: false,
  isOutDoorSpace: false,
  peopleInBaseRate: 1,
};
